# Generated by Django 5.0.2 on 2024-03-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyCosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('Hair cosmetics', 'Hair cosmetics'), ('Foundation', 'Foundation'), ('Concealer', 'Concealer'), ('Skincare', 'Skincare'), ('nails', 'nails'), ('Eyeshadow', 'Eyeshadow'), ('Bodycare', 'Bodycare'), ('Facemask', 'Facemask'), ('Lips', 'Lips')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.CreateModel(
            name='BooksAndStationery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('books', 'books'), ('notebook', 'notebook'), ('pen', 'pen'), ('bag', 'bag'), ('schoolset', 'schoolset')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.CreateModel(
            name='Eletronices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('Laptops', 'Laptops'), ('Phone', 'Phone'), ('Headphone', 'Headphone'), ('PC', 'PC'), ('speaker', 'speaker')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('fashion_name', models.CharField(max_length=100)),
                ('fashion_section', models.CharField(choices=[('M', 'mens'), ('F', 'female'), ('C', 'child')], max_length=20)),
                ('differentfashion', models.CharField(choices=[('Shirt', 'Shirt'), ('Trousers', 'Trousers'), ('T-Shirt', 'T-Shirt'), ('Formal', 'Formal'), ('Shorts', 'Shorts')], max_length=20)),
                ('size', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.CreateModel(
            name='HomeandKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('Productcatagory', models.CharField(choices=[('furniture', 'furniture'), ('Kitchen', 'Kitchen'), ('Cookware', 'Cookware')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.CreateModel(
            name='SportsOoutdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('sportscatagory', models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Badminton', 'Badminton'), ('Hocky', 'Hocky'), ('Tennis', 'Tennis')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
