# Generated by Django 5.0.2 on 2024-03-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0003_beautycosmetics_photo1_beautycosmetics_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautycosmetics',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booksandstationery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eletronices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='homeandkitchen',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Sportsandoutdoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('sportscatagory', models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Badminton', 'Badminton'), ('Hocky', 'Hocky'), ('Tennis', 'Tennis')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('photo1', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo2', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo3', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo4', models.ImageField(blank=True, upload_to='product_images/')),
                ('discount', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury.product')),
            ],
        ),
        migrations.DeleteModel(
            name='SportsOoutdoor',
        ),
    ]
